services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=llink-cluster
    volumes:
      - cassandra_data:/var/lib/cassandra
  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data
volumes:
  cassandra_data:
  redis_data: